"""Compatibility exports for repository internals.

New code should import the domain facade modules in ``app.repositories``.
"""

from __future__ import annotations

import logging

from app import download_policy, llm_policy
from app.repositories import (
    _alerts_retention as alerts_retention_repository,
)
from app.repositories import (
    _categories as categories_repository,
)
from app.repositories import (
    _channels as channels_repository,
)
from app.repositories import (
    _downloads as downloads_repository,
)
from app.repositories import (
    _llm as llm_repository,
)
from app.repositories import (
    _manual_articles as manual_articles_repository,
)
from app.repositories import (
    _manual_transcripts as manual_transcripts_repository,
)
from app.repositories import (
    _settings as settings_repository,
)
from app.repositories import (
    _transcripts as transcripts_repository,
)
from app.repositories import (
    _videos as videos_repository,
)

logger = logging.getLogger(__name__)

validate_download_output_dir = download_policy.validate_download_output_dir

LLM_PROVIDER_CODEX = llm_policy.LLM_PROVIDER_CODEX
LLM_PROVIDER_CLAUDE = llm_policy.LLM_PROVIDER_CLAUDE
LLM_PROVIDER_GEMINI = llm_policy.LLM_PROVIDER_GEMINI
LLM_PROVIDER_NONE = llm_policy.LLM_PROVIDER_NONE
LLM_PROVIDER_OPTIONS = llm_policy.LLM_PROVIDER_OPTIONS
LLM_PROVIDER_FALLBACK_OPTIONS = llm_policy.LLM_PROVIDER_FALLBACK_OPTIONS
LLM_PROMPT_TEMPLATE_MAX_LENGTH = llm_policy.LLM_PROMPT_TEMPLATE_MAX_LENGTH
LLM_CODEX_MODEL_DEFAULT = llm_policy.LLM_CODEX_MODEL_DEFAULT
LLM_CODEX_MODEL_VALUES = llm_policy.LLM_CODEX_MODEL_VALUES
LLM_GEMINI_MODEL_DEFAULT = llm_policy.LLM_GEMINI_MODEL_DEFAULT
LLM_REASONING_EFFORT_OPTIONS = llm_policy.LLM_REASONING_EFFORT_OPTIONS
LLM_REASONING_EFFORT_GEMINI_OPTIONS = llm_policy.LLM_REASONING_EFFORT_GEMINI_OPTIONS
normalize_llm_provider = llm_policy.normalize_llm_provider
normalize_codex_model = llm_policy.normalize_codex_model

WORKER_SETTING_KEY_MAP = settings_repository.WORKER_SETTING_KEY_MAP
WORKER_SETTING_DEFAULTS = settings_repository.WORKER_SETTING_DEFAULTS
RSS_BOOTSTRAP_LOOKBACK_DAYS_KEY = settings_repository.RSS_BOOTSTRAP_LOOKBACK_DAYS_KEY
RSS_BOOTSTRAP_LOOKBACK_DAYS_DEFAULT = settings_repository.RSS_BOOTSTRAP_LOOKBACK_DAYS_DEFAULT
RETENTION_DAYS_KEY = settings_repository.RETENTION_DAYS_KEY
RETENTION_DAYS_DEFAULT = settings_repository.RETENTION_DAYS_DEFAULT
RSS_FEED_MODE_KEY = settings_repository.RSS_FEED_MODE_KEY
RSS_FEED_MODE_DEFAULT = settings_repository.RSS_FEED_MODE_DEFAULT
RSS_FEED_MODE_OPTIONS = settings_repository.RSS_FEED_MODE_OPTIONS
VIDEOS_PER_PAGE_KEY = settings_repository.VIDEOS_PER_PAGE_KEY
VIDEOS_PER_PAGE_DEFAULT = settings_repository.VIDEOS_PER_PAGE_DEFAULT
LLM_PROVIDER_PRIMARY_KEY = settings_repository.LLM_PROVIDER_PRIMARY_KEY
LLM_PROVIDER_FALLBACK_KEY = settings_repository.LLM_PROVIDER_FALLBACK_KEY
LLM_PROMPT_TEMPLATE_KEY = settings_repository.LLM_PROMPT_TEMPLATE_KEY
LLM_MODEL_CODEX_KEY = settings_repository.LLM_MODEL_CODEX_KEY
LLM_MODEL_CLAUDE_KEY = settings_repository.LLM_MODEL_CLAUDE_KEY
LLM_MODEL_GEMINI_KEY = settings_repository.LLM_MODEL_GEMINI_KEY
LLM_REASONING_EFFORT_CODEX_KEY = settings_repository.LLM_REASONING_EFFORT_CODEX_KEY
LLM_REASONING_EFFORT_CLAUDE_KEY = settings_repository.LLM_REASONING_EFFORT_CLAUDE_KEY
LLM_REASONING_EFFORT_GEMINI_KEY = settings_repository.LLM_REASONING_EFFORT_GEMINI_KEY
LLM_RUNTIME_LAST_CODE_KEY = settings_repository.LLM_RUNTIME_LAST_CODE_KEY
LLM_RUNTIME_LAST_MESSAGE_KEY = settings_repository.LLM_RUNTIME_LAST_MESSAGE_KEY
LLM_RUNTIME_LAST_SEEN_AT_KEY = settings_repository.LLM_RUNTIME_LAST_SEEN_AT_KEY
LLM_PROVIDER_PRIMARY_DEFAULT = settings_repository.LLM_PROVIDER_PRIMARY_DEFAULT
LLM_PROVIDER_FALLBACK_DEFAULT = settings_repository.LLM_PROVIDER_FALLBACK_DEFAULT
LLM_MODEL_CLAUDE_MAX_LENGTH = settings_repository.LLM_MODEL_CLAUDE_MAX_LENGTH
LLM_MODEL_GEMINI_MAX_LENGTH = settings_repository.LLM_MODEL_GEMINI_MAX_LENGTH
TELEGRAM_BOT_TOKEN_KEY = settings_repository.TELEGRAM_BOT_TOKEN_KEY
TELEGRAM_CHAT_ID_KEY = settings_repository.TELEGRAM_CHAT_ID_KEY
TELEGRAM_BOT_TOKEN_MAX_LENGTH = settings_repository.TELEGRAM_BOT_TOKEN_MAX_LENGTH
TELEGRAM_CHAT_ID_MAX_LENGTH = settings_repository.TELEGRAM_CHAT_ID_MAX_LENGTH
get_settings_map = settings_repository.get_settings_map
get_setting = settings_repository.get_setting
set_setting = settings_repository.set_setting
get_worker_settings = settings_repository.get_worker_settings
set_worker_settings = settings_repository.set_worker_settings
is_worker_enabled = settings_repository.is_worker_enabled
get_policy_settings = settings_repository.get_policy_settings
set_policy_settings = settings_repository.set_policy_settings
get_videos_per_page_setting = settings_repository.get_videos_per_page_setting
set_videos_per_page_setting = settings_repository.set_videos_per_page_setting
get_telegram_settings = settings_repository.get_telegram_settings
set_telegram_settings = settings_repository.set_telegram_settings
get_llm_settings = settings_repository.get_llm_settings
set_llm_settings = settings_repository.set_llm_settings

CATEGORY_PROCESSING_STAGE_OFF = categories_repository.CATEGORY_PROCESSING_STAGE_OFF
CATEGORY_PROCESSING_STAGE_TRANSCRIPT_ONLY = (
    categories_repository.CATEGORY_PROCESSING_STAGE_TRANSCRIPT_ONLY
)
CATEGORY_PROCESSING_STAGE_FULL = categories_repository.CATEGORY_PROCESSING_STAGE_FULL
CATEGORY_PROCESSING_STAGE_OPTIONS = categories_repository.CATEGORY_PROCESSING_STAGE_OPTIONS
DEFAULT_CATEGORY_NAME = categories_repository.DEFAULT_CATEGORY_NAME
normalize_category_processing_stage = categories_repository.normalize_category_processing_stage
parse_category_processing_stage = categories_repository.parse_category_processing_stage
next_category_processing_stage = categories_repository.next_category_processing_stage
get_default_category_id = categories_repository.get_default_category_id
list_categories = categories_repository.list_categories
create_category = categories_repository.create_category
rename_category = categories_repository.rename_category
delete_category = categories_repository.delete_category
update_category_processing_stage = categories_repository.update_category_processing_stage
cycle_category_processing_stage = categories_repository.cycle_category_processing_stage
reorder_categories = categories_repository.reorder_categories
move_channels_to_category = categories_repository.move_channels_to_category

ALERT_TYPE_RSS_CHANNEL_NOT_FOUND = alerts_retention_repository.ALERT_TYPE_RSS_CHANNEL_NOT_FOUND
ALERT_TYPE_LLM_CONFIG_MISSING = alerts_retention_repository.ALERT_TYPE_LLM_CONFIG_MISSING
ALERT_TYPE_LLM_SCHEMA_INVALID = alerts_retention_repository.ALERT_TYPE_LLM_SCHEMA_INVALID
ALERT_TYPE_TELEGRAM_SEND_FAILED = alerts_retention_repository.ALERT_TYPE_TELEGRAM_SEND_FAILED
create_system_alert = alerts_retention_repository.create_system_alert
list_unacknowledged_alerts = alerts_retention_repository.list_unacknowledged_alerts
list_unacknowledged_alert_groups = alerts_retention_repository.list_unacknowledged_alert_groups
acknowledge_alert = alerts_retention_repository.acknowledge_alert
acknowledge_alerts_by_type = alerts_retention_repository.acknowledge_alerts_by_type
count_retention_expired_videos = alerts_retention_repository.count_retention_expired_videos
list_retention_expired_video_ids = alerts_retention_repository.list_retention_expired_video_ids
list_retention_expired_videos = alerts_retention_repository.list_retention_expired_videos

CHANNEL_MANAGEMENT_STATUS_ACTIVE = channels_repository.CHANNEL_MANAGEMENT_STATUS_ACTIVE
CHANNEL_MANAGEMENT_STATUS_INACTIVE = channels_repository.CHANNEL_MANAGEMENT_STATUS_INACTIVE
CHANNEL_MANAGEMENT_STATUS_OPTIONS = channels_repository.CHANNEL_MANAGEMENT_STATUS_OPTIONS
CHANNEL_METADATA_STATUS_NEVER = channels_repository.CHANNEL_METADATA_STATUS_NEVER
CHANNEL_METADATA_STATUS_PENDING = channels_repository.CHANNEL_METADATA_STATUS_PENDING
CHANNEL_METADATA_STATUS_RUNNING = channels_repository.CHANNEL_METADATA_STATUS_RUNNING
CHANNEL_METADATA_STATUS_SUCCESS = channels_repository.CHANNEL_METADATA_STATUS_SUCCESS
CHANNEL_METADATA_STATUS_FAILED = channels_repository.CHANNEL_METADATA_STATUS_FAILED
CHANNEL_METADATA_STATUS_RATE_LIMITED = channels_repository.CHANNEL_METADATA_STATUS_RATE_LIMITED
CHANNEL_METADATA_STATUS_OPTIONS = channels_repository.CHANNEL_METADATA_STATUS_OPTIONS
CHANNEL_METADATA_REFRESH_INTERVAL_DAYS_DEFAULT = (
    channels_repository.CHANNEL_METADATA_REFRESH_INTERVAL_DAYS_DEFAULT
)
CHANNEL_METADATA_RATE_LIMIT_BACKOFF_MINUTES = (
    channels_repository.CHANNEL_METADATA_RATE_LIMIT_BACKOFF_MINUTES
)
CHANNEL_METADATA_FAILURE_BACKOFF_MINUTES = (
    channels_repository.CHANNEL_METADATA_FAILURE_BACKOFF_MINUTES
)
CHANNEL_METADATA_MAX_RETRY_COUNT = channels_repository.CHANNEL_METADATA_MAX_RETRY_COUNT
normalize_channel_management_status = channels_repository.normalize_channel_management_status
normalize_channel_metadata_status = channels_repository.normalize_channel_metadata_status
list_channels = channels_repository.list_channels
list_channels_for_management = channels_repository.list_channels_for_management
get_channel_name_map = channels_repository.get_channel_name_map
count_channels_by_status = channels_repository.count_channels_by_status
add_channel = channels_repository.add_channel
get_channel_by_id = channels_repository.get_channel_by_id
enqueue_channel_metadata_refresh = channels_repository.enqueue_channel_metadata_refresh
schedule_channel_metadata_backfill = channels_repository.schedule_channel_metadata_backfill
claim_next_channel_metadata_target = channels_repository.claim_next_channel_metadata_target
mark_channel_metadata_succeeded = channels_repository.mark_channel_metadata_succeeded
mark_channel_metadata_failed = channels_repository.mark_channel_metadata_failed
enqueue_failed_channel_metadata = channels_repository.enqueue_failed_channel_metadata
recover_stuck_channel_metadata_running = channels_repository.recover_stuck_channel_metadata_running
deactivate_channel = channels_repository.deactivate_channel
reactivate_channel = channels_repository.reactivate_channel
reactivate_channels = channels_repository.reactivate_channels
list_active_channels = channels_repository.list_active_channels
update_channel_watermark = channels_repository.update_channel_watermark
delete_channels_with_related_data = channels_repository.delete_channels_with_related_data
pick_next_rss_channel = channels_repository.pick_next_rss_channel
mark_rss_poll_success = channels_repository.mark_rss_poll_success
increment_rss_fail_streak = channels_repository.increment_rss_fail_streak
touch_rss_last_polled_at = channels_repository.touch_rss_last_polled_at
count_active_channels = channels_repository.count_active_channels
is_newer_published = channels_repository.is_newer_published

VIDEO_LIST_FILTER_CORE_PIPELINE_STATUSES = (
    videos_repository.VIDEO_LIST_FILTER_CORE_PIPELINE_STATUSES
)
normalize_pipeline_status_filter = videos_repository.normalize_pipeline_status_filter
insert_video_if_absent = videos_repository.insert_video_if_absent
list_videos = videos_repository.list_videos
count_videos = videos_repository.count_videos
get_video = videos_repository.get_video
list_videos_by_ids = videos_repository.list_videos_by_ids
mark_video_viewed = videos_repository.mark_video_viewed
get_video_detail = videos_repository.get_video_detail
get_transcript = videos_repository.get_transcript
get_article = videos_repository.get_article
search_documents = videos_repository.search_documents
mark_video_retry = videos_repository.mark_video_retry
requeue_done_video_for_manual_article_retry = (
    videos_repository.requeue_done_video_for_manual_article_retry
)
update_video_thumbnail = videos_repository.update_video_thumbnail
delete_videos_by_ids = videos_repository.delete_videos_by_ids

TRANSCRIPT_GUARD_DEFAULTS = transcripts_repository.TRANSCRIPT_GUARD_DEFAULTS
TRANSCRIPT_ERROR_MESSAGE_MAX_LENGTH = transcripts_repository.TRANSCRIPT_ERROR_MESSAGE_MAX_LENGTH
TRANSCRIPT_REQUEST_HEADERS_OVERRIDES_KEY = (
    transcripts_repository.TRANSCRIPT_REQUEST_HEADERS_OVERRIDES_KEY
)
PIPELINE_STATUS_KEYS = transcripts_repository.PIPELINE_STATUS_KEYS
TRANSCRIPT_QUEUE_STATUSES = transcripts_repository.TRANSCRIPT_QUEUE_STATUSES
list_queue_items = transcripts_repository.list_queue_items
queue_status = transcripts_repository.queue_status
clear_transcript_queue_items = transcripts_repository.clear_transcript_queue_items
pop_pending_transcript_videos = transcripts_repository.pop_pending_transcript_videos
mark_transcript_processing = transcripts_repository.mark_transcript_processing
recover_stuck_transcript_jobs = transcripts_repository.recover_stuck_transcript_jobs
save_transcript = transcripts_repository.save_transcript
mark_no_subtitle = transcripts_repository.mark_no_subtitle
schedule_transcript_retry = transcripts_repository.schedule_transcript_retry
defer_channel_transcript_retries = transcripts_repository.defer_channel_transcript_retries
mark_transcript_failed = transcripts_repository.mark_transcript_failed
reset_transcript_for_retry = transcripts_repository.reset_transcript_for_retry
get_transcript_guard_state = transcripts_repository.get_transcript_guard_state
save_transcript_guard_state = transcripts_repository.save_transcript_guard_state
reset_transcript_guard_state = transcripts_repository.reset_transcript_guard_state
get_transcript_request_header_overrides = (
    transcripts_repository.get_transcript_request_header_overrides
)
save_transcript_request_header_overrides = (
    transcripts_repository.save_transcript_request_header_overrides
)

LLM_ARTICLE_PROVIDER_UNKNOWN = llm_repository.LLM_ARTICLE_PROVIDER_UNKNOWN
LLM_QUEUE_STATUSES = llm_repository.LLM_QUEUE_STATUSES
LLM_CONFIG_MISSING_ALERT_SENT_KEY = llm_repository.LLM_CONFIG_MISSING_ALERT_SENT_KEY
LLM_SCHEMA_INVALID_ALERT_SENT_KEY = llm_repository.LLM_SCHEMA_INVALID_ALERT_SENT_KEY
repair_orphan_llm_candidates = llm_repository.repair_orphan_llm_candidates
clear_llm_queue_items = llm_repository.clear_llm_queue_items
pop_llm_candidate = llm_repository.pop_llm_candidate
claim_next_llm_candidate = llm_repository.claim_next_llm_candidate
mark_restructure_processing = llm_repository.mark_restructure_processing
save_article = llm_repository.save_article
mark_restructure_failed = llm_repository.mark_restructure_failed
requeue_llm_pending_without_retry = llm_repository.requeue_llm_pending_without_retry
ensure_llm_config_missing_alert = llm_repository.ensure_llm_config_missing_alert
clear_llm_config_missing_alert_flag = llm_repository.clear_llm_config_missing_alert_flag
ensure_llm_schema_invalid_alert = llm_repository.ensure_llm_schema_invalid_alert
clear_llm_schema_invalid_alert_flag = llm_repository.clear_llm_schema_invalid_alert_flag
set_llm_runtime_issue = llm_repository.set_llm_runtime_issue
clear_llm_runtime_issue = llm_repository.clear_llm_runtime_issue
get_llm_runtime_issue = llm_repository.get_llm_runtime_issue
count_llm_pending_videos = llm_repository.count_llm_pending_videos

MANUAL_ARTICLE_ENQUEUE_SKIP_PIPELINE_STATUSES = (
    manual_articles_repository.MANUAL_ARTICLE_ENQUEUE_SKIP_PIPELINE_STATUSES
)
MANUAL_ARTICLE_ENQUEUE_RETRY_PIPELINE_STATUSES = (
    manual_articles_repository.MANUAL_ARTICLE_ENQUEUE_RETRY_PIPELINE_STATUSES
)
MANUAL_ARTICLE_JOB_STATUS_PENDING = manual_articles_repository.MANUAL_ARTICLE_JOB_STATUS_PENDING
MANUAL_ARTICLE_JOB_STATUS_RUNNING = manual_articles_repository.MANUAL_ARTICLE_JOB_STATUS_RUNNING
MANUAL_ARTICLE_JOB_STATUS_SUCCEEDED = manual_articles_repository.MANUAL_ARTICLE_JOB_STATUS_SUCCEEDED
MANUAL_ARTICLE_JOB_STATUS_FAILED = manual_articles_repository.MANUAL_ARTICLE_JOB_STATUS_FAILED
MANUAL_ARTICLE_JOB_STATUS_SKIPPED = manual_articles_repository.MANUAL_ARTICLE_JOB_STATUS_SKIPPED
MANUAL_ARTICLE_JOB_STATUS_OPTIONS = {
    MANUAL_ARTICLE_JOB_STATUS_PENDING,
    MANUAL_ARTICLE_JOB_STATUS_RUNNING,
    MANUAL_ARTICLE_JOB_STATUS_SUCCEEDED,
    MANUAL_ARTICLE_JOB_STATUS_FAILED,
    MANUAL_ARTICLE_JOB_STATUS_SKIPPED,
}
get_manual_article_job = manual_articles_repository.get_manual_article_job
get_active_manual_article_job_for_video = (
    manual_articles_repository.get_active_manual_article_job_for_video
)
enqueue_manual_article_jobs = manual_articles_repository.enqueue_manual_article_jobs
claim_next_manual_article_job = manual_articles_repository.claim_next_manual_article_job
mark_manual_article_job_succeeded = manual_articles_repository.mark_manual_article_job_succeeded
mark_manual_article_job_failed = manual_articles_repository.mark_manual_article_job_failed
mark_manual_article_job_skipped = manual_articles_repository.mark_manual_article_job_skipped
recover_stuck_manual_article_jobs = manual_articles_repository.recover_stuck_manual_article_jobs
ensure_video_llm_pending_for_manual_article = (
    manual_articles_repository.ensure_video_llm_pending_for_manual_article
)
force_mark_video_transcript_failed_for_manual_article = (
    manual_articles_repository.force_mark_video_transcript_failed_for_manual_article
)

MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES = (
    manual_transcripts_repository.MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES
)
MANUAL_TRANSCRIPT_JOB_STATUS_PENDING = (
    manual_transcripts_repository.MANUAL_TRANSCRIPT_JOB_STATUS_PENDING
)
MANUAL_TRANSCRIPT_JOB_STATUS_RUNNING = (
    manual_transcripts_repository.MANUAL_TRANSCRIPT_JOB_STATUS_RUNNING
)
MANUAL_TRANSCRIPT_JOB_STATUS_SUCCEEDED = (
    manual_transcripts_repository.MANUAL_TRANSCRIPT_JOB_STATUS_SUCCEEDED
)
MANUAL_TRANSCRIPT_JOB_STATUS_FAILED = (
    manual_transcripts_repository.MANUAL_TRANSCRIPT_JOB_STATUS_FAILED
)
MANUAL_TRANSCRIPT_JOB_STATUS_SKIPPED = (
    manual_transcripts_repository.MANUAL_TRANSCRIPT_JOB_STATUS_SKIPPED
)
MANUAL_TRANSCRIPT_JOB_STATUS_OPTIONS = {
    MANUAL_TRANSCRIPT_JOB_STATUS_PENDING,
    MANUAL_TRANSCRIPT_JOB_STATUS_RUNNING,
    MANUAL_TRANSCRIPT_JOB_STATUS_SUCCEEDED,
    MANUAL_TRANSCRIPT_JOB_STATUS_FAILED,
    MANUAL_TRANSCRIPT_JOB_STATUS_SKIPPED,
}
get_manual_transcript_job = manual_transcripts_repository.get_manual_transcript_job
get_active_manual_transcript_job_for_video = (
    manual_transcripts_repository.get_active_manual_transcript_job_for_video
)
enqueue_manual_transcript_job = manual_transcripts_repository.enqueue_manual_transcript_job
claim_next_manual_transcript_job = manual_transcripts_repository.claim_next_manual_transcript_job
mark_manual_transcript_job_succeeded = (
    manual_transcripts_repository.mark_manual_transcript_job_succeeded
)
mark_manual_transcript_job_failed = manual_transcripts_repository.mark_manual_transcript_job_failed
mark_manual_transcript_job_skipped = (
    manual_transcripts_repository.mark_manual_transcript_job_skipped
)
recover_stuck_manual_transcript_jobs = (
    manual_transcripts_repository.recover_stuck_manual_transcript_jobs
)

DOWNLOAD_QUALITY_OPTIONS = downloads_repository.DOWNLOAD_QUALITY_OPTIONS
DOWNLOAD_QUALITY_DEFAULT = downloads_repository.DOWNLOAD_QUALITY_DEFAULT
DOWNLOAD_DEFAULT_QUALITY_KEY = downloads_repository.DOWNLOAD_DEFAULT_QUALITY_KEY
DOWNLOAD_DEFAULT_OVERWRITE_KEY = downloads_repository.DOWNLOAD_DEFAULT_OVERWRITE_KEY
DOWNLOAD_DEFAULT_OUTPUT_DIR_KEY = downloads_repository.DOWNLOAD_DEFAULT_OUTPUT_DIR_KEY
DOWNLOAD_OUTPUT_DIR_DEFAULT = downloads_repository.DOWNLOAD_OUTPUT_DIR_DEFAULT
DOWNLOAD_STATUS_PENDING = downloads_repository.DOWNLOAD_STATUS_PENDING
DOWNLOAD_STATUS_RUNNING = downloads_repository.DOWNLOAD_STATUS_RUNNING
DOWNLOAD_STATUS_SUCCEEDED = downloads_repository.DOWNLOAD_STATUS_SUCCEEDED
DOWNLOAD_STATUS_FAILED = downloads_repository.DOWNLOAD_STATUS_FAILED
DOWNLOAD_STATUS_OPTIONS = downloads_repository.DOWNLOAD_STATUS_OPTIONS
normalize_download_quality = downloads_repository.normalize_download_quality
normalize_download_status_filter = downloads_repository.normalize_download_status_filter
get_download_default_settings = downloads_repository.get_download_default_settings
set_download_default_settings = downloads_repository.set_download_default_settings
get_download_job = downloads_repository.get_download_job
get_active_download_job_for_video = downloads_repository.get_active_download_job_for_video
create_download_job = downloads_repository.create_download_job
claim_next_download_job = downloads_repository.claim_next_download_job
mark_download_job_succeeded = downloads_repository.mark_download_job_succeeded
mark_download_job_failed = downloads_repository.mark_download_job_failed
retry_download_job = downloads_repository.retry_download_job
recover_stuck_download_jobs = downloads_repository.recover_stuck_download_jobs
count_download_jobs_by_status = downloads_repository.count_download_jobs_by_status
list_download_jobs = downloads_repository.list_download_jobs
count_download_jobs = downloads_repository.count_download_jobs
clear_download_jobs = downloads_repository.clear_download_jobs
latest_download_event_id = downloads_repository.latest_download_event_id
list_download_events_after = downloads_repository.list_download_events_after
get_download_progress = downloads_repository.get_download_progress
