"""Channel-related repository accessors."""

from app.repositories import _channels as repository

CHANNEL_MANAGEMENT_STATUS_ACTIVE = repository.CHANNEL_MANAGEMENT_STATUS_ACTIVE
CHANNEL_MANAGEMENT_STATUS_INACTIVE = repository.CHANNEL_MANAGEMENT_STATUS_INACTIVE
CHANNEL_MANAGEMENT_STATUS_OPTIONS = repository.CHANNEL_MANAGEMENT_STATUS_OPTIONS

CHANNEL_METADATA_STATUS_NEVER = repository.CHANNEL_METADATA_STATUS_NEVER
CHANNEL_METADATA_STATUS_PENDING = repository.CHANNEL_METADATA_STATUS_PENDING
CHANNEL_METADATA_STATUS_RUNNING = repository.CHANNEL_METADATA_STATUS_RUNNING
CHANNEL_METADATA_STATUS_SUCCESS = repository.CHANNEL_METADATA_STATUS_SUCCESS
CHANNEL_METADATA_STATUS_FAILED = repository.CHANNEL_METADATA_STATUS_FAILED
CHANNEL_METADATA_STATUS_RATE_LIMITED = repository.CHANNEL_METADATA_STATUS_RATE_LIMITED

normalize_channel_management_status = repository.normalize_channel_management_status
normalize_channel_metadata_status = repository.normalize_channel_metadata_status

list_channels = repository.list_channels
list_channels_for_management = repository.list_channels_for_management
get_channel_name_map = repository.get_channel_name_map
count_channels_by_status = repository.count_channels_by_status
add_channel = repository.add_channel
get_channel_by_id = repository.get_channel_by_id

enqueue_channel_metadata_refresh = repository.enqueue_channel_metadata_refresh
schedule_channel_metadata_backfill = repository.schedule_channel_metadata_backfill
claim_next_channel_metadata_target = repository.claim_next_channel_metadata_target
mark_channel_metadata_succeeded = repository.mark_channel_metadata_succeeded
mark_channel_metadata_failed = repository.mark_channel_metadata_failed
enqueue_failed_channel_metadata = repository.enqueue_failed_channel_metadata
recover_stuck_channel_metadata_running = repository.recover_stuck_channel_metadata_running

deactivate_channel = repository.deactivate_channel
reactivate_channel = repository.reactivate_channel
reactivate_channels = repository.reactivate_channels
list_active_channels = repository.list_active_channels
update_channel_watermark = repository.update_channel_watermark

delete_channels_with_related_data = repository.delete_channels_with_related_data

pick_next_rss_channel = repository.pick_next_rss_channel
mark_rss_poll_success = repository.mark_rss_poll_success
increment_rss_fail_streak = repository.increment_rss_fail_streak
touch_rss_last_polled_at = repository.touch_rss_last_polled_at
count_active_channels = repository.count_active_channels
is_newer_published = repository.is_newer_published
