"""Channel-related repository accessors."""

import app.repositories._channels as repository
import app.repositories._channels_metadata as metadata_repository
import app.repositories._channels_polling as polling_repository

CHANNEL_MANAGEMENT_STATUS_ACTIVE = repository.CHANNEL_MANAGEMENT_STATUS_ACTIVE
CHANNEL_MANAGEMENT_STATUS_INACTIVE = repository.CHANNEL_MANAGEMENT_STATUS_INACTIVE
CHANNEL_MANAGEMENT_STATUS_OPTIONS = repository.CHANNEL_MANAGEMENT_STATUS_OPTIONS

CHANNEL_METADATA_STATUS_NEVER = repository.CHANNEL_METADATA_STATUS_NEVER
CHANNEL_METADATA_STATUS_PENDING = repository.CHANNEL_METADATA_STATUS_PENDING
CHANNEL_METADATA_STATUS_RUNNING = repository.CHANNEL_METADATA_STATUS_RUNNING
CHANNEL_METADATA_STATUS_SUCCESS = repository.CHANNEL_METADATA_STATUS_SUCCESS
CHANNEL_METADATA_STATUS_FAILED = repository.CHANNEL_METADATA_STATUS_FAILED
CHANNEL_METADATA_STATUS_RATE_LIMITED = repository.CHANNEL_METADATA_STATUS_RATE_LIMITED
ChannelDeletionResult = repository.ChannelDeletionResult
RSS_PRIORITY_PINNED = polling_repository.RSS_PRIORITY_PINNED
RSS_PRIORITY_NORMAL = polling_repository.RSS_PRIORITY_NORMAL
RSS_PRIORITY_LOW = polling_repository.RSS_PRIORITY_LOW
RSS_PRIORITY_OPTIONS = polling_repository.RSS_PRIORITY_OPTIONS

normalize_channel_management_status = repository.normalize_channel_management_status
normalize_channel_metadata_status = repository.normalize_channel_metadata_status
normalize_rss_priority = polling_repository.normalize_rss_priority

list_channels = repository.list_channels
list_channels_for_management = repository.list_channels_for_management
get_channel_name_map = repository.get_channel_name_map
count_channels_by_status = repository.count_channels_by_status
add_channel = repository.add_channel
get_channel_by_id = repository.get_channel_by_id

enqueue_channel_metadata_refresh = metadata_repository.enqueue_channel_metadata_refresh
schedule_channel_metadata_backfill = metadata_repository.schedule_channel_metadata_backfill
claim_next_channel_metadata_target = metadata_repository.claim_next_channel_metadata_target
mark_channel_metadata_succeeded = metadata_repository.mark_channel_metadata_succeeded
mark_channel_metadata_failed = metadata_repository.mark_channel_metadata_failed
enqueue_failed_channel_metadata = metadata_repository.enqueue_failed_channel_metadata
recover_stuck_channel_metadata_running = metadata_repository.recover_stuck_channel_metadata_running

deactivate_channel = repository.deactivate_channel
reactivate_channel = repository.reactivate_channel
reactivate_channels = repository.reactivate_channels
list_active_channels = repository.list_active_channels
update_channel_watermark = repository.update_channel_watermark

delete_channels_with_related_data = repository.delete_channels_with_related_data

pick_next_rss_channel = polling_repository.pick_next_rss_channel
mark_rss_poll_success = polling_repository.mark_rss_poll_success
increment_rss_fail_streak = polling_repository.increment_rss_fail_streak
touch_rss_last_polled_at = polling_repository.touch_rss_last_polled_at
update_rss_cache = polling_repository.update_rss_cache
get_seconds_until_next_rss_poll = polling_repository.get_seconds_until_next_rss_poll
update_rss_priority = polling_repository.update_rss_priority
count_active_channels = polling_repository.count_active_channels
is_newer_published = polling_repository.is_newer_published
