"""Download domain repository accessors."""

from app.repositories import _downloads as repository
from app.repositories import _downloads_queries as queries_repository

DOWNLOAD_QUALITY_OPTIONS = repository.DOWNLOAD_QUALITY_OPTIONS
DOWNLOAD_QUALITY_DEFAULT = repository.DOWNLOAD_QUALITY_DEFAULT
DOWNLOAD_STATUS_PENDING = repository.DOWNLOAD_STATUS_PENDING
DOWNLOAD_STATUS_RUNNING = repository.DOWNLOAD_STATUS_RUNNING
DOWNLOAD_STATUS_SUCCEEDED = repository.DOWNLOAD_STATUS_SUCCEEDED
DOWNLOAD_STATUS_FAILED = repository.DOWNLOAD_STATUS_FAILED

normalize_download_quality = repository.normalize_download_quality
normalize_download_status_filter = repository.normalize_download_status_filter

get_download_default_settings = repository.get_download_default_settings
set_download_default_settings = repository.set_download_default_settings

get_download_job = repository.get_download_job
get_active_download_job_for_video = repository.get_active_download_job_for_video
create_download_job = repository.create_download_job
claim_next_download_job = repository.claim_next_download_job
mark_download_job_succeeded = repository.mark_download_job_succeeded
mark_download_job_failed = repository.mark_download_job_failed
retry_download_job = repository.retry_download_job
recover_stuck_download_jobs = repository.recover_stuck_download_jobs
count_download_jobs_by_status = queries_repository.count_download_jobs_by_status
list_download_jobs = queries_repository.list_download_jobs
count_download_jobs = queries_repository.count_download_jobs
clear_download_jobs = repository.clear_download_jobs
latest_download_event_id = queries_repository.latest_download_event_id
list_download_events_after = queries_repository.list_download_events_after
get_download_progress = queries_repository.get_download_progress
