"""LLM pipeline repository accessors."""

from app import repository as legacy

LLM_QUEUE_STATUSES = legacy.LLM_QUEUE_STATUSES
ALERT_TYPE_LLM_SCHEMA_INVALID = legacy.ALERT_TYPE_LLM_SCHEMA_INVALID
LLM_SCHEMA_INVALID_ALERT_SENT_KEY = legacy.LLM_SCHEMA_INVALID_ALERT_SENT_KEY

repair_orphan_llm_candidates = legacy.repair_orphan_llm_candidates
pop_llm_candidate = legacy.pop_llm_candidate
mark_restructure_processing = legacy.mark_restructure_processing
save_article = legacy.save_article
mark_restructure_failed = legacy.mark_restructure_failed
requeue_llm_pending_without_retry = legacy.requeue_llm_pending_without_retry

ensure_llm_config_missing_alert = legacy.ensure_llm_config_missing_alert
clear_llm_config_missing_alert_flag = legacy.clear_llm_config_missing_alert_flag
ensure_llm_schema_invalid_alert = legacy.ensure_llm_schema_invalid_alert
clear_llm_schema_invalid_alert_flag = legacy.clear_llm_schema_invalid_alert_flag
set_llm_runtime_issue = legacy.set_llm_runtime_issue
clear_llm_runtime_issue = legacy.clear_llm_runtime_issue
get_llm_runtime_issue = legacy.get_llm_runtime_issue
count_llm_pending_videos = legacy.count_llm_pending_videos
get_llm_settings = legacy.get_llm_settings
