"""Manual transcript job repository accessors."""

import app.repositories._manual_transcripts as repository

MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES = repository.MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES

enqueue_manual_transcript_job = repository.enqueue_manual_transcript_job
claim_next_manual_transcript_job = repository.claim_next_manual_transcript_job
mark_manual_transcript_job_succeeded = repository.mark_manual_transcript_job_succeeded
mark_manual_transcript_job_failed = repository.mark_manual_transcript_job_failed
mark_manual_transcript_job_skipped = repository.mark_manual_transcript_job_skipped
recover_stuck_manual_transcript_jobs = repository.recover_stuck_manual_transcript_jobs
