"""Manual transcript job repository accessors."""

from app.repositories import _manual_transcripts as repository

MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES = repository.MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES
MANUAL_TRANSCRIPT_JOB_STATUS_PENDING = repository.MANUAL_TRANSCRIPT_JOB_STATUS_PENDING
MANUAL_TRANSCRIPT_JOB_STATUS_RUNNING = repository.MANUAL_TRANSCRIPT_JOB_STATUS_RUNNING
MANUAL_TRANSCRIPT_JOB_STATUS_SUCCEEDED = repository.MANUAL_TRANSCRIPT_JOB_STATUS_SUCCEEDED
MANUAL_TRANSCRIPT_JOB_STATUS_FAILED = repository.MANUAL_TRANSCRIPT_JOB_STATUS_FAILED
MANUAL_TRANSCRIPT_JOB_STATUS_SKIPPED = repository.MANUAL_TRANSCRIPT_JOB_STATUS_SKIPPED

get_manual_transcript_job = repository.get_manual_transcript_job
get_active_manual_transcript_job_for_video = repository.get_active_manual_transcript_job_for_video
enqueue_manual_transcript_job = repository.enqueue_manual_transcript_job
claim_next_manual_transcript_job = repository.claim_next_manual_transcript_job
mark_manual_transcript_job_succeeded = repository.mark_manual_transcript_job_succeeded
mark_manual_transcript_job_failed = repository.mark_manual_transcript_job_failed
mark_manual_transcript_job_skipped = repository.mark_manual_transcript_job_skipped
recover_stuck_manual_transcript_jobs = repository.recover_stuck_manual_transcript_jobs
