"""Manual article job repository accessors."""

import app.repositories._manual_articles as repository

MANUAL_ARTICLE_ENQUEUE_SKIP_PIPELINE_STATUSES = (
    repository.MANUAL_ARTICLE_ENQUEUE_SKIP_PIPELINE_STATUSES
)

get_manual_article_job = repository.get_manual_article_job
get_active_manual_article_job_for_video = repository.get_active_manual_article_job_for_video
enqueue_manual_article_jobs = repository.enqueue_manual_article_jobs
claim_next_manual_article_job = repository.claim_next_manual_article_job
mark_manual_article_job_succeeded = repository.mark_manual_article_job_succeeded
mark_manual_article_job_failed = repository.mark_manual_article_job_failed
mark_manual_article_job_skipped = repository.mark_manual_article_job_skipped
recover_stuck_manual_article_jobs = repository.recover_stuck_manual_article_jobs
ensure_video_llm_pending_for_manual_article = repository.ensure_video_llm_pending_for_manual_article
force_mark_video_transcript_failed_for_manual_article = (
    repository.force_mark_video_transcript_failed_for_manual_article
)
