"""Manual transcript job repository accessors."""

from app import repository as legacy

MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES = legacy.MANUAL_TRANSCRIPT_ALLOWED_PIPELINE_STATUSES
MANUAL_TRANSCRIPT_JOB_STATUS_PENDING = legacy.MANUAL_TRANSCRIPT_JOB_STATUS_PENDING
MANUAL_TRANSCRIPT_JOB_STATUS_RUNNING = legacy.MANUAL_TRANSCRIPT_JOB_STATUS_RUNNING
MANUAL_TRANSCRIPT_JOB_STATUS_SUCCEEDED = legacy.MANUAL_TRANSCRIPT_JOB_STATUS_SUCCEEDED
MANUAL_TRANSCRIPT_JOB_STATUS_FAILED = legacy.MANUAL_TRANSCRIPT_JOB_STATUS_FAILED
MANUAL_TRANSCRIPT_JOB_STATUS_SKIPPED = legacy.MANUAL_TRANSCRIPT_JOB_STATUS_SKIPPED

get_manual_transcript_job = legacy.get_manual_transcript_job
get_active_manual_transcript_job_for_video = legacy.get_active_manual_transcript_job_for_video
enqueue_manual_transcript_job = legacy.enqueue_manual_transcript_job
claim_next_manual_transcript_job = legacy.claim_next_manual_transcript_job
mark_manual_transcript_job_succeeded = legacy.mark_manual_transcript_job_succeeded
mark_manual_transcript_job_failed = legacy.mark_manual_transcript_job_failed
mark_manual_transcript_job_skipped = legacy.mark_manual_transcript_job_skipped
recover_stuck_manual_transcript_jobs = legacy.recover_stuck_manual_transcript_jobs
